"""student web login

Revision ID: a57dda8dc711
Revises: c115eb3b6fcf
Create Date: 2026-10-03 23:07:15.439934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a57dda8dc711'
down_revision: Union[str, Sequence[str], None] = 'c115eb3b6fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkrequest',
    sa.Column('state_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_table('studentlogincode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studentlogincode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studentlogincode_student_id'), ['student_id'], unique=False)

    op.create_table('studentsession',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('studentsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studentsession_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('consent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('consent_version')
        batch_op.drop_column('consent_at')

    with op.batch_alter_table('studentsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studentsession_student_id'))

    op.drop_table('studentsession')
    with op.batch_alter_table('studentlogincode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studentlogincode_student_id'))

    op.drop_table('studentlogincode')
    op.drop_table('linkrequest')
    # ### end Alembic commands ###
