"""initial schema

Revision ID: c115eb3b6fcf
Revises: 
Create Date: 2026-10-03 18:31:44.974637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'c115eb3b6fcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendarentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendarentry_key'), ['key'], unique=False)

    op.create_table('course',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('messagelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linked', sa.Boolean(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unanswered_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messagelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messagelog_created_at'), ['created_at'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_student_number'), ['student_number'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('apitoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apitoken_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitoken_token_hash'), ['token_hash'], unique=True)

    op.create_table('authsession',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authsession_user_id'), ['user_id'], unique=False)

    op.create_table('channelaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id')
    )
    with op.batch_alter_table('channelaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channelaccount_student_id'), ['student_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective', sa.Date(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_code')
    )
    op.create_table('handoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('office', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handoff_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_handoff_student_id'), ['student_id'], unique=False)

    op.create_table('lecturercourse',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_code')
    )
    op.create_table('linkcode',
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('code_hash')
    )
    with op.batch_alter_table('linkcode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linkcode_student_id'), ['student_id'], unique=False)

    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('send_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_send_at'), ['send_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_student_id'), ['student_id'], unique=False)

    op.create_table('scheduleitem',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('where', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('scheduleitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduleitem_course_code'), ['course_code'], unique=False)

    op.create_table('handoffevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handoff_id'], ['handoff.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoffevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handoffevent_handoff_id'), ['handoff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handoffevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handoffevent_handoff_id'))

    op.drop_table('handoffevent')
    with op.batch_alter_table('scheduleitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduleitem_course_code'))

    op.drop_table('scheduleitem')
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_student_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_send_at'))

    op.drop_table('reminder')
    with op.batch_alter_table('linkcode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkcode_student_id'))

    op.drop_table('linkcode')
    op.drop_table('lecturercourse')
    with op.batch_alter_table('handoff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handoff_student_id'))
        batch_op.drop_index(batch_op.f('ix_handoff_reference'))

    op.drop_table('handoff')
    op.drop_table('enrollment')
    op.drop_table('document')
    with op.batch_alter_table('channelaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channelaccount_student_id'))

    op.drop_table('channelaccount')
    with op.batch_alter_table('authsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authsession_user_id'))

    op.drop_table('authsession')
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apitoken_token_hash'))
        batch_op.drop_index(batch_op.f('ix_apitoken_student_id'))

    op.drop_table('apitoken')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_number'))

    op.drop_table('student')
    with op.batch_alter_table('messagelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messagelog_created_at'))

    op.drop_table('messagelog')
    op.drop_table('course')
    with op.batch_alter_table('calendarentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendarentry_key'))

    op.drop_table('calendarentry')
    # ### end Alembic commands ###
